name: Deploy mdBook to GitHub Pages

on:
  push:
    branches: [doc-manual]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install mdBook
        uses: peaceiris/actions-mdbook@v1
      - name: Build mdBook
        run: mdbook build docs/manual
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/manual/book
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
